/**
 * Command encapsulating the fields required to create or update a driver
 * via POST /api/v1/drivers or PUT /api/v1/drivers/{id}.
 * idCompany must match the JWT companyId — resolved from IamStore, never from the UI.
 * username/password are auto-generated by the backend.
 */
export class SaveDriverCommand {
  readonly email:         string;
  readonly fullName:      string;
  readonly idCompany:     number;
  readonly licenseNumber: string;
  readonly workShift:     string;
  readonly id?:           number;

  constructor(props: {
    email:         string;
    fullName:      string;
    idCompany:     number;
    licenseNumber: string;
    workShift:     string;
    id?:           number;
  }) {
    this.email         = props.email;
    this.fullName      = props.fullName;
    this.idCompany     = props.idCompany;
    this.licenseNumber = props.licenseNumber;
    this.workShift     = props.workShift;
    this.id            = props.id;
  }
}
