/**
 * Command encapsulating the fields required to create or update a driver
 * via POST /api/v1/drivers or PATCH /api/v1/drivers/{id}.
 *
 * @remarks
 * The tenant (`companyId`) is resolved server-side from the JWT and is **never**
 * sent from the UI — the `POST /drivers` DTO is annotated
 * `@JsonIgnoreProperties(ignoreUnknown = false)`, so any extra field (including
 * `idCompany`, `username`, `password`) is rejected with `400`.
 * username/password are auto-generated by the backend and emailed to the driver.
 */
export class SaveDriverCommand {
  readonly email:         string;
  readonly fullName:      string;
  readonly licenseNumber: string;
  readonly workShift:     string;
  readonly id?:           number;

  constructor(props: {
    email:         string;
    fullName:      string;
    licenseNumber: string;
    workShift:     string;
    id?:           number;
  }) {
    this.email         = props.email;
    this.fullName      = props.fullName;
    this.licenseNumber = props.licenseNumber;
    this.workShift     = props.workShift;
    this.id            = props.id;
  }
}
