export const environment = {
  production: false,
  platformProviderApiBaseUrl: 'https://mineguard-api-wmr0.onrender.com',
  platformProviderSignInEndpointPath: '/authentication/sign-in',
  platformProviderSignUpEndpointPath: '/authentication/sign-up',
  platformProviderDashboardSummaryEndpointPath: '/dashboardSummary',
  platformProviderDashboardTrendEndpointPath: '/dashboardTrend',
  platformProviderDashboardRiskDriversEndpointPath: '/dashboardRiskDrivers',
  platformProviderDashboardRecentAlertsEndpointPath: '/dashboardRecentAlerts',
  platformProviderPerformanceMetricsEndpointPath: '/performanceMetrics',
  platformProviderReportsEndpointPath: '/reports',
  platformProviderAnalyticsFatigueBarsEndpointPath: '/analyticsFatigueBars',
  platformProviderAnalyticsIncidentDistributionEndpointPath: '/analyticsIncidentDistribution',
  platformProviderAnalyticsHistoryRowsEndpointPath: '/analyticsHistoryRows',
  platformProviderAnalyticsInsightsEndpointPath: '/analyticsInsights',
  platformProviderAdminSummaryEndpointPath: '/adminSummary',
  platformProviderAdminNoticesEndpointPath: '/adminNotices',
  platformProviderSupervisorsEndpointPath: '/supervisors',
  platformProviderAuditLogEndpointPath: '/auditLog',
  platformProviderCatalogSummaryEndpointPath: '/catalogSummary',
  platformProviderVehiclesInventoryEndpointPath: '/vehiclesInventory',
  platformProviderDriversDirectoryEndpointPath: '/driversDirectory',
  platformProviderOperationalAlertsEndpointPath: '/operationalAlerts',
  platformProviderLiveMapVehiclesEndpointPath: '/liveMapVehicles',
  platformProviderFleetSummaryEndpointPath: '/fleetSummary',
  platformProviderCardiacReadingsEndpointPath: '/cardiacReadings',
};
