import { HttpClient } from '@angular/common/http';
import { Observable, catchError, map } from 'rxjs';

import { environment } from '../../../environments/environment';
import { ErrorHandlingEnabledBaseType } from '../../shared/infrastructure/error-handling-enabled-base-type';
import { SaveDriverCommand } from '../domain/model/save-driver.command';
import { DriverResource } from './driver-response';

/**
 * Body for POST /api/v1/drivers (`CreateDriverResource`).
 * Only these fields are accepted — the DTO is `@JsonIgnoreProperties(ignoreUnknown = false)`,
 * so any extra property (`idCompany`, `username`, `password`) is rejected with `400`.
 * `companyId` is resolved from the JWT; `workerId`/temporary password are generated server-side.
 */
interface CreateDriverBody {
  fullName:      string;
  licenseNumber: string;
  email?:        string;
  workShift?:    string;
}

/**
 * Body for PATCH /api/v1/drivers/{id} (`UpdateDriverResource`).
 * Every field is independently optional — omitted fields keep their current value.
 */
interface UpdateDriverBody {
  fullName?:      string;
  licenseNumber?: string;
  email?:         string;
  workShift?:     string;
}

const endpointUrl = `${environment.platformProviderApiBaseUrl}${environment.platformProviderDriversEndpointPath}`;

/**
 * HTTP endpoint client for POST /api/v1/drivers and PATCH /api/v1/drivers/{id}.
 *
 * @remarks
 * The tenant is resolved server-side from the JWT — no company field is ever sent.
 * username/password are auto-generated by the backend; this client never submits them.
 */
export class DriversWriteApiEndpoint extends ErrorHandlingEnabledBaseType {
  constructor(private http: HttpClient) {
    super();
  }

  create(command: SaveDriverCommand): Observable<DriverResource> {
    return this.http.post<DriverResource>(endpointUrl, this.toCreateBody(command)).pipe(
      map((res) => res),
      catchError(this.handleError('Failed to create driver')),
    );
  }

  update(command: SaveDriverCommand): Observable<DriverResource> {
    return this.http.patch<DriverResource>(`${endpointUrl}/${command.id}`, this.toUpdateBody(command)).pipe(
      map((res) => res),
      catchError(this.handleError('Failed to update driver')),
    );
  }

  getById(id: number): Observable<DriverResource> {
    return this.http.get<DriverResource>(`${endpointUrl}/${id}`).pipe(
      catchError(this.handleError(`Failed to fetch driver ${id}`)),
    );
  }

  /**
   * DELETE /api/v1/drivers/{id} — soft-delete (sets shiftStatus=INACTIVE).
   * The raw error is left unwrapped so the caller can read `status`/`details`.
   */
  deactivate(id: number): Observable<void> {
    return this.http.delete<void>(`${endpointUrl}/${id}`);
  }

  private toCreateBody(command: SaveDriverCommand): CreateDriverBody {
    return {
      fullName:      command.fullName,
      licenseNumber: command.licenseNumber,
      email:         command.email     || undefined,
      workShift:     command.workShift || undefined,
    };
  }

  private toUpdateBody(command: SaveDriverCommand): UpdateDriverBody {
    return {
      fullName:      command.fullName,
      licenseNumber: command.licenseNumber,
      email:         command.email     || undefined,
      workShift:     command.workShift || undefined,
    };
  }
}
